language:
- python
python:
- '3.6'
- '3.5'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: Ye0leRMU/5C1B376eyTRJkZXxrmwGnoynMHy3vBvUZZS4gfhMfxchyVNYjPXoXH4LUAm79CQ2LC1pnDYv6E5g7hYKDGPn2clKu7LKEBjxmYIA0HDAP/6wSfXK6MrvKd72u3RsBMU68y76v+qlu0UDyAHdCEPN5/B1lKlfmuoA/KQQdGXDblRJLl2gJVv/3EkGjtOZAAFsz+NhsrNiycvYWh4CB5YthHHzIV90qMEXowH361RhNOMPJVcjp8ZA+ZuhXJrVwVt8v8MawcMoC6RslszSbueeHvUmbpX5nk175eVOWTkDYsO6jEuuE6AkjkwFeiNpGxBZdKn/nCsicqEItvhDTsfdoKF0K82JT/a912oHwzze/RKDNS9V54nGfHhtnSl3YUuBXLE0Gutnx5NJrTgw6URjcGSr0Mm0c+pPh6Gsw9QdsQN0w1jeOxWrMYTX+DDJTbQtt7+KaHWSQZ4i+j8fwtu/6NXERM9SNUFIkhYKXjJEW/aM/BlOlYeET41gww9OrZovGx6T8n8ry+afqTlSxodvMm3lCc7tKyz4zbFdQnbvtQvLErUj43IZfJ/k8kqArNiMSkvAoditycR7UAqv9r2rOONhS/bthzoz7mRuVOM93CSTt8aMbiAFqU4CPZ8ACo2yn9oD0SI1J+JlYPRZtxHnlvnHNX/TExjbsY=
  app: FlaskTaskManager-10
  on:
    repo: SandipanGhosh/FlaskTaskManager-10
